#!/bin/ksh
#
# How to type password (passphrase) only once:
#	cd
#	ssh-keygen -t rsa # Press "Enter", then 2x type non-empty(!) passphrase
#	cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys2
#

MPIEXEC=${MPIEXEC-"mpptest"}
MPIOPTS=${MPIOPTS-"-nolocal"}
#MPIHOSTS=${MPIHOSTS-"merlin"}
#MPIHOSTS=${MPIHOSTS-"pcn103-10 pcn103-11 pcn103-12 pcn103-13"}


#pcm105-01 
#MMPIHOSTS="pcm105-00 pcm105-02 pcm105-03 pcm105-04 pcm105-05 pcm105-09 pcm105-10 pcm105-11 pcm105-12 pcm105-13 pcm105-14 pcm105-15 pcm105-16 pcm105-17"

#pcn104-01 pcn104-03 pcn104-04 pcn104-05 pcn104-06 pcn104-08 pcn104-09 pcn104-19
NMPIHOSTS="pcn104-12 pcn104-13 pcn104-14 pcn104-15 pcn104-16 pcn104-17 pcn105-00 pcn105-01 pcn105-02 pcn105-03 pcn105-04 pcn105-05 pcn105-07 pcn105-08 pcn105-09 pcn105-10 pcn105-11 pcn105-12 pcn105-13 pcn105-14 pcn105-15 pcn105-16 pcn105-17 pcn104-19"
#pcn104-10 pcn104-11 

OMPIHOSTS="pco103-00 pco103-01 pco103-03 pco103-04 pco103-05 pco103-06 pco103-07"
#pco103-08 pco103-09 pco103-15 pco103-16 pco104-17"}
# pco103-13 pco103-14 pco103-10 pco103-11 pco103-12  pco103-17 pco103-18 pco103-19

LMPIHOSTS="pcl204-00 pcl204-03 pcl204-09 pcl204-12 pcl204-15 pcl204-16 pcl204-17 pcl204-19"
#NMPIHOSTS="pcn203-02 pcn203-03 pcn204-04 pcn204-05"

MPIHOSTS=${MPIHOSTS-"$NMPIHOSTS $OMPIHOSTS $LMPIHOSTS"}



#for i in $MPIHOSTS; do
#ssh $i exit;
#done

APP_NAME=${APP_NAME-"testOneMax"}

if [ $# -eq 0 ] ; then
    cnt=0
    for i in $MPIHOSTS;
    do
        echo "Killing in $i"
        ssh $i killall -s 9 $APP_NAME
        let cnt=cnt+1
    done
    echo "$cnt machines available"

	echo "Usage: `basename $0` number_of_processes [executable]"
	exit
fi
NP=$1
shift
if [ $# -ge 1 ] ; then
	MPIEXEC=$1
	shift
fi
TMP=/tmp/`basename $0`.$$
test -f $TMP && exit 1
trap "" 2 3 15
echo "$MPIHOSTS" | tr " " "\012" > $TMP
#eval `ssh-agent` >/dev/null
#ssh-add >/dev/null
mpirun -np $NP $MPIOPTS -machinefile $TMP $MPIEXEC "$@"
test -f $TMP && rm $TMP
#eval `ssh-agent -k` >/dev/null
