# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gridsmainwindow.ui'
#
# Created: Mon Dec  9 11:48:10 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_GridsMainWindow(object):
    def setupUi(self, GridsMainWindow):
        GridsMainWindow.setObjectName("GridsMainWindow")
        GridsMainWindow.resize(703, 834)
        GridsMainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralWidget = QtGui.QWidget(GridsMainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 7, 1, 1)
        self.label = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.ySizeSpinBox = QtGui.QSpinBox(self.centralWidget)
        self.ySizeSpinBox.setProperty("value", 31)
        self.ySizeSpinBox.setObjectName("ySizeSpinBox")
        self.gridLayout.addWidget(self.ySizeSpinBox, 1, 5, 1, 1)
        self.gISpinBox = QtGui.QSpinBox(self.centralWidget)
        self.gISpinBox.setReadOnly(False)
        self.gISpinBox.setProperty("value", 15)
        self.gISpinBox.setObjectName("gISpinBox")
        self.gridLayout.addWidget(self.gISpinBox, 1, 2, 1, 1)
        self.xSizeSpinBox = QtGui.QSpinBox(self.centralWidget)
        self.xSizeSpinBox.setProperty("value", 31)
        self.xSizeSpinBox.setObjectName("xSizeSpinBox")
        self.gridLayout.addWidget(self.xSizeSpinBox, 0, 5, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 6, 1, 1)
        self.gESpinBox = QtGui.QSpinBox(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gESpinBox.sizePolicy().hasHeightForWidth())
        self.gESpinBox.setSizePolicy(sizePolicy)
        self.gESpinBox.setReadOnly(False)
        self.gESpinBox.setProperty("value", 5)
        self.gESpinBox.setObjectName("gESpinBox")
        self.gridLayout.addWidget(self.gESpinBox, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.noise_sigmaSpinBox = QtGui.QSpinBox(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noise_sigmaSpinBox.sizePolicy().hasHeightForWidth())
        self.noise_sigmaSpinBox.setSizePolicy(sizePolicy)
        self.noise_sigmaSpinBox.setMaximum(300)
        self.noise_sigmaSpinBox.setSingleStep(150)
        self.noise_sigmaSpinBox.setObjectName("noise_sigmaSpinBox")
        self.gridLayout.addWidget(self.noise_sigmaSpinBox, 0, 8, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 9, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(5, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 10, 1, 1)
        self.autoLoadCheckBox = QtGui.QCheckBox(self.centralWidget)
        self.autoLoadCheckBox.setChecked(True)
        self.autoLoadCheckBox.setTristate(False)
        self.autoLoadCheckBox.setObjectName("autoLoadCheckBox")
        self.gridLayout.addWidget(self.autoLoadCheckBox, 0, 11, 1, 1)
        self.useNoiseSigmaCheckBox = QtGui.QCheckBox(self.centralWidget)
        self.useNoiseSigmaCheckBox.setChecked(False)
        self.useNoiseSigmaCheckBox.setObjectName("useNoiseSigmaCheckBox")
        self.gridLayout.addWidget(self.useNoiseSigmaCheckBox, 1, 11, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 7, 1, 1)
        self.subDirLineEdit = QtGui.QLineEdit(self.centralWidget)
        self.subDirLineEdit.setObjectName("subDirLineEdit")
        self.gridLayout.addWidget(self.subDirLineEdit, 2, 8, 1, 1)
        self.trialNumSpinBox = QtGui.QSpinBox(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trialNumSpinBox.sizePolicy().hasHeightForWidth())
        self.trialNumSpinBox.setSizePolicy(sizePolicy)
        self.trialNumSpinBox.setObjectName("trialNumSpinBox")
        self.gridLayout.addWidget(self.trialNumSpinBox, 1, 8, 1, 1)
        self.label_9 = QtGui.QLabel(self.centralWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 7, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.groupBox_2 = QtGui.QGroupBox(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.loadLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.loadLineEdit.setReadOnly(False)
        self.loadLineEdit.setObjectName("loadLineEdit")
        self.horizontalLayout_2.addWidget(self.loadLineEdit)
        self.selectButton = QtGui.QPushButton(self.groupBox_2)
        self.selectButton.setObjectName("selectButton")
        self.horizontalLayout_2.addWidget(self.selectButton)
        self.loadButton = QtGui.QPushButton(self.groupBox_2)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_2.addWidget(self.loadButton)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.gridsTab = QtGui.QWidget()
        self.gridsTab.setObjectName("gridsTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gridsTab)
        self.verticalLayout_2.setSpacing(-1)
        self.verticalLayout_2.setContentsMargins(5, -1, 5, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(self.gridsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridSweepWidget = GridSweepWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridSweepWidget.sizePolicy().hasHeightForWidth())
        self.gridSweepWidget.setSizePolicy(sizePolicy)
        self.gridSweepWidget.setMinimumSize(QtCore.QSize(400, 350))
        self.gridSweepWidget.setMaximumSize(QtCore.QSize(400, 350))
        self.gridSweepWidget.setObjectName("gridSweepWidget")
        self.horizontalLayout_3.addWidget(self.gridSweepWidget)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.gridExamplesLayout = QtGui.QHBoxLayout()
        self.gridExamplesLayout.setObjectName("gridExamplesLayout")
        self.gridFieldWidget = GridFieldWidget(self.gridsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridFieldWidget.sizePolicy().hasHeightForWidth())
        self.gridFieldWidget.setSizePolicy(sizePolicy)
        self.gridFieldWidget.setMinimumSize(QtCore.QSize(200, 200))
        self.gridFieldWidget.setMaximumSize(QtCore.QSize(200, 200))
        self.gridFieldWidget.setObjectName("gridFieldWidget")
        self.gridExamplesLayout.addWidget(self.gridFieldWidget)
        self.aCorrWidget = ACorrelationWidget(self.gridsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aCorrWidget.sizePolicy().hasHeightForWidth())
        self.aCorrWidget.setSizePolicy(sizePolicy)
        self.aCorrWidget.setMinimumSize(QtCore.QSize(200, 200))
        self.aCorrWidget.setMaximumSize(QtCore.QSize(200, 200))
        self.aCorrWidget.setObjectName("aCorrWidget")
        self.gridExamplesLayout.addWidget(self.aCorrWidget)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridExamplesLayout.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.gridExamplesLayout)
        self.tabWidget.addTab(self.gridsTab, "")
        self.bumpsTab = QtGui.QWidget()
        self.bumpsTab.setObjectName("bumpsTab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.bumpsTab)
        self.verticalLayout_3.setContentsMargins(5, -1, 5, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_3 = QtGui.QGroupBox(self.bumpsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bumpSweepWidget = BumpSweepWidget(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bumpSweepWidget.sizePolicy().hasHeightForWidth())
        self.bumpSweepWidget.setSizePolicy(sizePolicy)
        self.bumpSweepWidget.setMinimumSize(QtCore.QSize(400, 350))
        self.bumpSweepWidget.setMaximumSize(QtCore.QSize(400, 350))
        self.bumpSweepWidget.setObjectName("bumpSweepWidget")
        self.horizontalLayout_4.addWidget(self.bumpSweepWidget)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.bumpExamplesLayout = QtGui.QHBoxLayout()
        self.bumpExamplesLayout.setContentsMargins(-1, 5, -1, -1)
        self.bumpExamplesLayout.setObjectName("bumpExamplesLayout")
        self.eFRExampleWidget = EFRWidget(self.bumpsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eFRExampleWidget.sizePolicy().hasHeightForWidth())
        self.eFRExampleWidget.setSizePolicy(sizePolicy)
        self.eFRExampleWidget.setMinimumSize(QtCore.QSize(200, 200))
        self.eFRExampleWidget.setMaximumSize(QtCore.QSize(200, 200))
        self.eFRExampleWidget.setObjectName("eFRExampleWidget")
        self.bumpExamplesLayout.addWidget(self.eFRExampleWidget)
        self.iFRExampleWidget = IFRWidget(self.bumpsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iFRExampleWidget.sizePolicy().hasHeightForWidth())
        self.iFRExampleWidget.setSizePolicy(sizePolicy)
        self.iFRExampleWidget.setMinimumSize(QtCore.QSize(200, 200))
        self.iFRExampleWidget.setMaximumSize(QtCore.QSize(200, 200))
        self.iFRExampleWidget.setObjectName("iFRExampleWidget")
        self.bumpExamplesLayout.addWidget(self.iFRExampleWidget)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setContentsMargins(-1, 10, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label_8 = QtGui.QLabel(self.bumpsTab)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.bumpSigmaLabel = QtGui.QLabel(self.bumpsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bumpSigmaLabel.sizePolicy().hasHeightForWidth())
        self.bumpSigmaLabel.setSizePolicy(sizePolicy)
        self.bumpSigmaLabel.setMinimumSize(QtCore.QSize(75, 0))
        self.bumpSigmaLabel.setMaximumSize(QtCore.QSize(75, 16777215))
        self.bumpSigmaLabel.setText("")
        self.bumpSigmaLabel.setObjectName("bumpSigmaLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.bumpSigmaLabel)
        self.bumpExamplesLayout.addLayout(self.formLayout)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.bumpExamplesLayout.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.bumpExamplesLayout)
        self.tabWidget.addTab(self.bumpsTab, "")
        self.gammaTab = QtGui.QWidget()
        self.gammaTab.setObjectName("gammaTab")
        self.tabWidget.addTab(self.gammaTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        GridsMainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(GridsMainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.useNoiseSigmaCheckBox, QtCore.SIGNAL("toggled(bool)"), self.noise_sigmaSpinBox.setEnabled)
        QtCore.QObject.connect(self.useNoiseSigmaCheckBox, QtCore.SIGNAL("toggled(bool)"), self.subDirLineEdit.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(GridsMainWindow)

    def retranslateUi(self, GridsMainWindow):
        GridsMainWindow.setWindowTitle(QtGui.QApplication.translate("GridsMainWindow", "Grid data interactive visualisation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("GridsMainWindow", "Noise sigma", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("GridsMainWindow", "gE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("GridsMainWindow", "gI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("GridsMainWindow", "X size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("GridsMainWindow", "Y size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("GridsMainWindow", "pA", None, QtGui.QApplication.UnicodeUTF8))
        self.autoLoadCheckBox.setText(QtGui.QApplication.translate("GridsMainWindow", "Automatic data load", None, QtGui.QApplication.UnicodeUTF8))
        self.useNoiseSigmaCheckBox.setText(QtGui.QApplication.translate("GridsMainWindow", "Use noise sigma value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("GridsMainWindow", "Sub-directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("GridsMainWindow", "Trial no.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("GridsMainWindow", "Input directory", None, QtGui.QApplication.UnicodeUTF8))
        self.selectButton.setText(QtGui.QApplication.translate("GridsMainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setText(QtGui.QApplication.translate("GridsMainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("GridsMainWindow", "Sweeps", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gridsTab), QtGui.QApplication.translate("GridsMainWindow", "Grids", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("GridsMainWindow", "Sweeps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("GridsMainWindow", "Bump sigma:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bumpsTab), QtGui.QApplication.translate("GridsMainWindow", "Bumps", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gammaTab), QtGui.QApplication.translate("GridsMainWindow", "Gamma", None, QtGui.QApplication.UnicodeUTF8))

from mplwidget import GridSweepWidget, IFRWidget, EFRWidget, ACorrelationWidget, GridFieldWidget, BumpSweepWidget
